name: Convert PPTX to PDF and Generate List

on:
  push:
    branches:
      - main

jobs:
  convert-and-generate:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install LibreOffice
        run: |
          sudo apt-get update
          sudo apt-get install -y libreoffice

      - name: Convert PPTX to PDF
        run: |
          mkdir -p slides-pdf
          for file in slides/*.pptx slides/*.ppt; do
            if [ -f "$file" ]; then
              echo "Converting $file..."
              libreoffice --headless --convert-to pdf "$file" --outdir slides-pdf
            fi
          done
          ls -l slides-pdf

      - name: Copy PDFs to docs
        run: |
          mkdir -p docs/pdfs
          cp slides-pdf/*.pdf docs/pdfs || true
          ls -l docs/pdfs

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Generate pdf-list.json
        run: |
          npm install fs-extra
          node scripts/generate-index.js

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/pdfs/*.pdf docs/pdf-list.json
          git commit -m "Update PDFs & pdf-list.json [skip ci]" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
